### ISSUE TITLE
Bug in making snapshots

### ISSUE THREAD

**Issue by verveerpj** [equinor/webviz-core-components#74]
Users of the webviz-based everviz reported  a problem where they could not make a snapshot of a plot, when it was the second plot on a page.

The online webviz demo shows that the same happens in webviz:

If there is more than one entry in the content of a page, each of these get their own snapshot button. The first of those works fine, the second does not produce a plot, or an incomplete plot. It is reproducible with the online Reek WEbviz example, on the page "Correlation between input parameters and response".

**Comment by anders-kiaer** [comment]
Thanks for the report @verveerpj. :tada: I can reproduce it as well.

Instead of https://github.com/equinor/webviz-core-components/blob/eb678d33139380389467f962a23390bd7aced5ef/package.json#L29 I pinned the version to `html2canvas==0.5.0-beta4` and built `webviz-core-components` - then this was gone. Going to the next release, `1.0.0-alpha.1`, introduces again the problem, indicating that this is a problem in the dependency `html2canvas`. Using the `0.5` version is not feasible as I can see, as that `html2canvas` version apparently lack important features like respecting a broad range of CSS styles when creating the corresponding canvas/image.

I see there might be some issues over at `html2canvas` already that might be related, like https://github.com/niklasvh/html2canvas/issues/1992.

Not sure how to best proceed. Three options (in semi-prioritized order):
1) See if we can help out in `html2canvas` to detect the bug. However, this could quickly end up being unfeasible since the code base is unknown. The [0.5.0-beta4 (working) - 0.1.0-alpha.1 (not working) comparison](https://github.com/niklasvh/html2canvas/compare/v0.5.0-beta4...v1.0.0-alpha.1) also indicates this could be challenging, as between those versions there was apparently a complete rewrite of the package.
2) Any other actively maintained package doing the same with a decent user community we could switch to?
3) Any workarounds we should implement (apparently it works when placed at the top...)?

**Comment by anders-kiaer** [comment]
Looks like the issue is not directly related to number of plugins/dashboards on a single page (even though it easily becomes more apparent there). Rather it is connected to the scrollbar (even a single dashboard on a page is cropped a bit if scrolling down a bit first).
